### PR TITLE
Update requirements.txt for Odoo Version 11 to 16

### PR DESCRIPTION
**Pull request by kafai-lam**
Copied [requirements.txt](https://github.com/odoo/odoo/blob/15.0/requirements.txt) from several odoo versions (from 11 to 16)

### CODE REVIEW

**Comment by llacroix** [comment]
Thank you for the contribution.

The reason the requirements.txt are in this repository is because they are modified to have less strict requirements. Odoo requirements files are uselessly too strict and prevent it from using native libraries when it's possible. 

For example, odoo requirements require gevent 1.1.2 . Let say your distribution provide gevent 1.1.3 with a python-gevent package. When installing the requirements it will try to uninstall 1.1.3 and compile 1.1.2. But in order to do that, you have to install binaries to compile code like build-essential and python-dev. That's all completely useless when 1.1.3 would work just fine.  

If I wanted to use the copy of requirements.txt, I'd use them from the repository itself when it is cloned.

If you want to add a requirements for 16.0 I'm not against it keep the version as relaxed as 15.0 as much as possible.

**Comment by llacroix** [comment]
You can see the pipeline fails for various reasons, usually it's gevent/lxml/psycopg2 that are the most problematic. So please don't modify existing requirements unless you add an issue installing something. 

And enable tests for odoo 16 in   https://github.com/llacroix/odoo-tools/blob/main/.github/workflows/python-package.yml#L20-L25

**Comment by kafai-lam** [comment]
@llacroix Thank you for the great job on this tools! it helps me a lot. 

I got a small issue when I setup odoo env through odoo-tools with command `odootools manage setup 15.0`

Odoo server failed to start and I have to install library `cryptography` with version `cryptography==2.6.1` to make it works.

I understand your concern. Maybe I close this PR first since it contains lot of changes which are not related to my main purpose. I will create a new issue about my problem.

**Comment by llacroix** [comment]
It remind me of something between pyopenssl, cryptography and requests. 

Installing `requests[security]` can solve all those incompatibilities issue as it will install the right version of pyopenssl then the dependencies of pyopenssl force the right version of cryptography.

But you're right, the cryptography should at least be a dependency. I see it's a change in the requirements that dates from 16 days ago. So it seems fairly new. 

The only modules that directly depend on cryptography in odoo15 are l10n_es_edi, account_edi_proxy_client and on enterprise there's the sale_ebay module.

Do you have issue with this module?

It would be nice if you can post the error that prevents odoo from starting.

**Pull request closed without merging**
